project:
  type: book

book:
  title: "Hacking Religion: TRS & Data Science in Action"
  author: "Jeremy H. Kidwell"
  date: "9/29/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - chapter_1.qmd
    - chapter_2.qmd
    - chapter_3.qmd
    - chapter_4.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



